# 1.ndarry
## 特性
### 多维性

In [1]:
import numpy as np

In [ ]:
arr = np.array(5)           #0维数组
print(arr)
print('Dimension:',arr.ndim)

5
Dimension: 0


In [ ]:
arr = np.array([1,2,3,4,5]) #1维数组
print(arr)
print('Dimension:',arr.ndim)

[1 2 3 4 5]
Dimension: 1


In [8]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])    #2维数组
print(arr)
print('Dimension:',arr.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Dimension: 2


### 同质性

In [10]:
arr = np.array([1,'Hello'])
print(arr)

['1' 'Hello']
