# ndarry
## 特性
### 多维性

In [1]:
import numpy as np

In [ ]:
arr = np.array(5)           #0维数组
print(arr)
print('Dimension:',arr.ndim)

5
Dimension: 0


In [ ]:
arr = np.array([1,2,3,4,5]) #1维数组
print(arr)
print('Dimension:',arr.ndim)

[1 2 3 4 5]
Dimension: 1


In [8]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])    #2维数组
print(arr)
print('Dimension:',arr.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Dimension: 2


### 同质性

In [10]:
arr = np.array([1,'Hello'])
print(arr)

['1' 'Hello']


In [11]:
arr = np.array([1,2.5,5])
print(arr)

[1.  2.5 5. ]


## 数组属性
- shape：数组的形状（行属于列数）
- ndim:维度
- size：元素个数
- dtype：元素类型
- T：转秩
- itemsize：单个元素占用内存大小
- nbytes：占用内存总量
- flags：是否连续存储

In [17]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print("arr shape",arr.shape)
print("arr dimension",arr.ndim)
print("arr size",arr.size)
print("arr data type",arr.dtype)
print("arr T\n",arr.T)
print("arr item size",arr.itemsize)
print("arr memory size",arr.nbytes)
print("是否连续:\n",arr.flags)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
arr shape (3, 3)
arr dimension 2
arr size 9
arr data type int64
arr T
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
arr item size 8
arr memory size 72
是否连续:
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [2]:
import pandas as pd
print(pd.__version__)

3.0.3


In [3]:
import numpy as np
# 创建一维数组
arr1 = np.zeros(5)
print(arr1)  # [0. 0. 0. 0. 0.]

# 创建二维数组
arr2 = np.zeros((3, 4))
print(arr2)
# [[0. 0. 0. 0.]
#  [0. 0. 0. 0.]
#  [0. 0. 0. 0.]]

# 指定数据类型
arr3 = np.zeros(5, dtype=int)
print(arr3)  # [0 0 0 0 0]

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0 0 0 0 0]
