# NumPy 成绩分析实验室

这是一个 NumPy 入门小项目。我们会用一组学生成绩数据，练习数组创建、属性查看、索引切片、统计分析、布尔筛选、排序排名和广播运算。

项目目标：

- 理解 `ndarray` 的基本结构
- 熟悉 `axis=0` 和 `axis=1`
- 学会用 NumPy 进行批量计算
- 用布尔条件筛选数据
- 完成一个小型数据分析流程

## 1. 导入 NumPy

In [2]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 1.26.4


## 2. 准备成绩数据

这里用二维数组表示成绩：

- 每一行代表一个学生
- 每一列代表一个科目

In [3]:
students = np.array(["小明", "小红", "小刚", "小丽", "小强", "小雅"])
subjects = np.array(["语文", "数学", "英语", "科学"])

scores = np.array([
    [88, 92, 85, 90],
    [95, 89, 94, 91],
    [76, 81, 79, 85],
    [90, 96, 93, 97],
    [68, 75, 72, 70],
    [84, 88, 90, 86],
])

print("学生：", students)
print("科目：", subjects)
print("成绩表：")
print(scores)

学生： ['小明' '小红' '小刚' '小丽' '小强' '小雅']
科目： ['语文' '数学' '英语' '科学']
成绩表：
[[88 92 85 90]
 [95 89 94 91]
 [76 81 79 85]
 [90 96 93 97]
 [68 75 72 70]
 [84 88 90 86]]


## 3. 查看 ndarray 属性

学习 NumPy 时，先养成看数组属性的习惯：维度、形状、元素数量和数据类型。

In [4]:
print("维度 ndim:", scores.ndim)
print("形状 shape:", scores.shape)
print("元素数量 size:", scores.size)
print("数据类型 dtype:", scores.dtype)

维度 ndim: 2
形状 shape: (6, 4)
元素数量 size: 24
数据类型 dtype: int32


## 4. 索引和切片

二维数组索引格式：`数组[行, 列]`。

In [5]:
print("第 1 个学生的所有成绩：", scores[0])
print("第 1 个学生的数学成绩：", scores[0, 1])
print("所有学生的数学成绩：", scores[:, 1])
print("前 3 个学生的语文和数学成绩：")
print(scores[:3, :2])

第 1 个学生的所有成绩： [88 92 85 90]
第 1 个学生的数学成绩： 92
所有学生的数学成绩： [92 89 81 96 75 88]
前 3 个学生的语文和数学成绩：
[[88 92]
 [95 89]
 [76 81]]


## 5. 按科目统计

`axis=0` 表示沿着行方向压缩，也就是对每一列做统计。这里可以理解为“每个科目的统计”。

In [6]:
subject_mean = scores.mean(axis=0)
subject_max = scores.max(axis=0)
subject_min = scores.min(axis=0)

for subject, mean_score, max_score, min_score in zip(subjects, subject_mean, subject_max, subject_min):
    print(f"{subject}: 平均分={mean_score:.1f}, 最高分={max_score}, 最低分={min_score}")

语文: 平均分=83.5, 最高分=95, 最低分=68
数学: 平均分=86.8, 最高分=96, 最低分=75
英语: 平均分=85.5, 最高分=94, 最低分=72
科学: 平均分=86.5, 最高分=97, 最低分=70


## 6. 按学生统计

`axis=1` 表示沿着列方向压缩，也就是对每一行做统计。这里可以理解为“每个学生的统计”。

In [7]:
student_total = scores.sum(axis=1)
student_mean = scores.mean(axis=1)

for name, total, mean_score in zip(students, student_total, student_mean):
    print(f"{name}: 总分={total}, 平均分={mean_score:.1f}")

小明: 总分=355, 平均分=88.8
小红: 总分=369, 平均分=92.2
小刚: 总分=321, 平均分=80.2
小丽: 总分=376, 平均分=94.0
小强: 总分=285, 平均分=71.2
小雅: 总分=348, 平均分=87.0


## 7. 找出最高分学生和最强科目

In [8]:
best_student_index = np.argmax(student_mean)
best_subject_index = np.argmax(subject_mean)

print("平均分最高的学生：", students[best_student_index])
print("该学生平均分：", student_mean[best_student_index])
print("平均分最高的科目：", subjects[best_subject_index])
print("该科目平均分：", subject_mean[best_subject_index])

平均分最高的学生： 小丽
该学生平均分： 94.0
平均分最高的科目： 数学
该科目平均分： 86.83333333333333


## 8. 布尔筛选

布尔筛选是 NumPy 很常用的能力。先得到一组 `True` / `False`，再用它筛选数组。

In [9]:
excellent_mask = student_mean >= 90

print("是否优秀：", excellent_mask)
print("优秀学生：", students[excellent_mask])
print("优秀学生平均分：", student_mean[excellent_mask])

是否优秀： [False  True False  True False False]
优秀学生： ['小红' '小丽']
优秀学生平均分： [92.25 94.  ]


In [10]:
weak_mask = scores < 80
weak_positions = np.where(weak_mask)

for row, col in zip(weak_positions[0], weak_positions[1]):
    print(f"{students[row]} 的 {subjects[col]} 需要加强：{scores[row, col]} 分")

小刚 的 语文 需要加强：76 分
小刚 的 英语 需要加强：79 分
小强 的 语文 需要加强：68 分
小强 的 数学 需要加强：75 分
小强 的 英语 需要加强：72 分
小强 的 科学 需要加强：70 分


## 9. 排名

`np.argsort` 返回的是排序后的索引。默认从小到大，想从高到低可以加 `[::-1]`。

In [11]:
ranking_index = np.argsort(student_mean)[::-1]

print("平均分排名：")
for rank, index in enumerate(ranking_index, start=1):
    print(f"第 {rank} 名：{students[index]}，平均分 {student_mean[index]:.1f}")

平均分排名：
第 1 名：小丽，平均分 94.0
第 2 名：小红，平均分 92.2
第 3 名：小明，平均分 88.8
第 4 名：小雅，平均分 87.0
第 5 名：小刚，平均分 80.2
第 6 名：小强，平均分 71.2


## 10. 广播机制

广播可以让不同形状的数组进行批量运算。下面给每个科目设置不同加分。

In [12]:
bonus = np.array([2, 0, 3, 1])
new_scores = scores + bonus

print("原始成绩：")
print(scores)
print("加分后成绩：")
print(new_scores)

原始成绩：
[[88 92 85 90]
 [95 89 94 91]
 [76 81 79 85]
 [90 96 93 97]
 [68 75 72 70]
 [84 88 90 86]]
加分后成绩：
[[90 92 88 91]
 [97 89 97 92]
 [78 81 82 86]
 [92 96 96 98]
 [70 75 75 71]
 [86 88 93 87]]


## 11. 随机模拟练习

用随机数模拟 10 个学生、4 个科目的成绩，再做一次统计。

In [13]:
rng = np.random.default_rng(seed=42)
random_scores = rng.integers(60, 101, size=(10, 4))

print(random_scores)
print("每个学生平均分：", random_scores.mean(axis=1))
print("每个科目平均分：", random_scores.mean(axis=0))

[[ 63  91  86  77]
 [ 77  95  63  88]
 [ 68  63  81 100]
 [ 90  91  89  92]
 [ 81  65  94  78]
 [ 80  75  67  97]
 [ 92  86  76  93]
 [ 82  78  78  69]
 [ 63  82  96  62]
 [ 95  93  71  85]]
每个学生平均分： [79.25 80.75 78.   90.5  79.5  79.75 86.75 76.75 75.75 86.  ]
每个科目平均分： [79.1 81.9 80.1 84.1]


## 12. 课后小练习

你可以继续在下面添加代码，完成这些任务：

- 找出数学成绩最高的学生
- 找出所有科目都大于等于 85 分的学生
- 计算每个学生最高分和最低分的差距
- 把所有低于 80 分的成绩加 5 分，但最高不能超过 100 分
- 自己增加一个新学生，并重新计算排名

In [14]:
# 在这里写你的练习代码
maxmath = np.max(random_scores[:, 1])
print("数学最高分：", maxmath)

数学最高分： 95
